name: "ninja-install"
description: "Installs the Ninja build system"
inputs:
  version:
    description: "The Ninja version to install"
    required: false
    default: "1.11.1"
runs:
  using: "composite"
  steps:
    - name: Export Ninja version in environment
      shell: bash
      run: |
        echo "NINJA_VERSION=${{ inputs.version }}" >> $GITHUB_ENV

    - name: "Linux installation"
      if: runner.os == 'Linux'
      shell: bash
      run: |
        wget https://github.com/ninja-build/ninja/releases/download/v${NINJA_VERSION}/ninja-linux.zip
        unzip -d /home/runner/.ninja/ ninja-linux.zip
        echo "/home/runner/.ninja" >> $GITHUB_PATH

    - name: "Windows installation"
      if: runner.os == 'Windows'
      shell: bash
      run: |
        mkdir ninja
        cd ninja
        curl -kLSs https://github.com/ninja-build/ninja/releases/download/v${NINJA_VERSION}/ninja-win.zip -o ninja-win.zip
        unzip -d /home/runner/.ninja ninja-win.zip
        echo "/home/runner/.ninja" >> $GITHUB_PATH

    - name: "MacOS installation"
      if: runner.os == 'MacOS'
      shell: bash
      run: |
        wget https://github.com/ninja-build/ninja/releases/download/v${NINJA_VERSION}/ninja-mac.zip
        unzip -d /home/runner/.ninja ninja-mac.zip
        echo "/home/runner/.ninja" >> $GITHUB_PATH
